### ISSUE TITLE
Compilation error: 'fwd2' is not a member of 'purify::FFTOperator'

### ISSUE THREAD

**Issue by olebole** [basp-group/purify#7] opened 2016-10-11 15:50 UTC
When I try to compile on Debian unstable, I get the following errors:

```
cd /build/purify-2.0.0/obj-x86_64-linux-gnu/cpp/purify && /usr/lib/ccache/c++   -Dlibpurify_EXPORTS -I/build/purify-2.0.0/obj-x86_64-linux-gnu/include -I/build/purify-2.
/build/purify-2.0.0/cpp/purify/FFTOperator.cc: In member function 'purify::Matrix<std::complex<double> > purify::FFTOperator::forward(purify::Matrix<std::complex<double>
/build/purify-2.0.0/cpp/purify/FFTOperator.cc:137:3: error: 'fwd2' is not a member of 'purify::FFTOperator'
   FFTOperator::fwd2(dest, input, fftw_flag_, only_plan);
   ^~~~~~~~~~~
/build/purify-2.0.0/cpp/purify/FFTOperator.cc: In member function 'purify::Matrix<std::complex<double> > purify::FFTOperator::inverse(purify::Matrix<std::complex<double>
/build/purify-2.0.0/cpp/purify/FFTOperator.cc:142:3: error: 'inv2' is not a member of 'purify::FFTOperator'
   FFTOperator::inv2(dest, input, fftw_flag_, only_plan);
   ^~~~~~~~~~~
/build/purify-2.0.0/cpp/purify/FFTOperator.cc: In member function 'void purify::FFTOperator::set_up_multithread()':
/build/purify-2.0.0/cpp/purify/FFTOperator.cc:151:3: error: 'clear_plans' is not a member of 'purify::FFTOperator'
   FFTOperator::clear_plans();
   ^~~~~~~~~~~
cpp/purify/CMakeFiles/libpurify.dir/build.make:89: recipe for target 'cpp/purify/CMakeFiles/libpurify.dir/FFTOperator.cc.o' failed
```

`FFTOperator.h` includes `<unsupported/Eigen/FFT>`, which has commented out `fwd2`:

```
    /*
    inline 
    void fwd2(Complex * dst, const Complex * src, int n0,int n1)
    {
      m_impl.fwd2(dst,src,n0,n1);
    }
    */
```

Looking into the [eigen3 repository](https://bitbucket.org/eigen/eigen/annotate/1a24287c6c133b46f8929cf5a4550e270ab66025/unsupported/Eigen/FFT?at=default&fileviewer=file-view-default#FFT-200) however shows that `fwd2` has commented out since 2010 (???).

Any glue here?

**Comment by Luke-Pratley** [comment] 2016-10-13 20:45
Hi @olebole ,
The problem is that we updated Eigen, but have not merged it with the public version. CMake downloads the updated version of Eigen from https://bitbucket.org/LukePratley/eigen, but it requires mercurial to be installed to do the command `hg clone`.

I have talked to the others about changing the CMake build to download Eigen without mercurial. However, if you want to build this version of Eigen yourself, you can use https://bitbucket.org/LukePratley/eigen/get/3.2.tar.gz .

Luke

**Comment by olebole** [comment] 2016-10-13 20:49
Could you give me the diff between your patched version and the public version?
I just cannot build a private version of eigen during the package build of purify.
What I could do is to take the official header files, copy them into the source tree of purify and then apply the updates.

**Comment by Luke-Pratley** [comment] 2016-10-13 21:03
The differences can be found at https://bitbucket.org/LukePratley/eigen/branch/3.2 . As far as I can tell, it is just the headers `unsupported/Eigen/FFT` and `unsupported/Eigen/src/FFT/ei_fftw_impl.h`. You should be able to copy them from the 3.2.tar.gz file

**Comment by mdavezac** [comment] 2016-10-14 14:09
@olebole, the plan is to submit the changes upstream. We just have not had time to review them quite as well as we should for that. It's still at the stage of "works for us", rather than "fits sensibly inside Eigen". That's all on me though.

**Comment by olebole** [comment] 2016-10-14 14:15
I extracted the diff and [put it to our Debian subdir](https://github.com/kernsuite-debian/purify/blob/master/debian/eigen3_LukePratley.patch); it applies without problems to the eigen3 version in Debian. ~~I still didn't test that it compiles, though ...~~. This make (at least) this part compile well.

**Closed as completed** 2016-10-14 15:29 UTC

**Comment by olebole** [comment] 2016-10-14 20:58
I could get it compiled and (with some more fixes, I will report in the next days) install.

Just for the records (and for the required copyright documentation in Debian): the changes you @Luke-Pratley made are copyrighted by you, and they are [under MPL as (most of) the rest of the Eigen3 package](http://eigen.tuxfamily.org/index.php?title=Main_Page#License), right?
